config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    resources :events
    resources :projects
  end

  resources :members

  scope '/projects/:project_id' do
    resources :todos
  end

  root to: 'home#index'
  
end

app/models/event.rb
# -*- coding: utf-8 -*-
class Event < ActiveRecord::Base

  VALID_ACTION_LIST = [
                       :create_todo,         # 创建任务
                       :edit_todo_deadlines, # 修改截至日期
                       :create_project,      # 创建项目
                       :start_todo,          # 开始处理任务
                       :reopen_todo,         # 重新打开任务
                       :complete_todo,       # 完成任务
                       :suspend_todo,        # 暂停处理任务
                       :reply_todo_list,     # 回复任务清单
                       :create_todo_list,    # 创建任务清单
                       :move_todo,           # 移动任务
                       :comment_todo,        # 评论任务
                       :assign_todo,         # 指派任务,
                       :edit_assign_todo,    # 修改任务完成者
                       :create_team,         # 创建团队
                       :praise_comment,      # 赞评论
                       :delete_comment,      # 删除回复
                       :delete_todo,         # 删除任务
                       :recover_todo,        # 恢复任务
                       :create_schedule,     # 创建日程
                       :edit_schedule,       # 编辑日程
                       :delete_schedule      # 删除日程
                      ].map(&:to_s).freeze

  # 事件发生时所属的源，比如 project, todo, 日程等
  belongs_to :source, polymorphic: true

  # 事件所属的资源，比如 team, project, calendar
  belongs_to :resource, polymorphic: true
  
  belongs_to :user
  belongs_to :team

  validates :action, inclusion: {in: VALID_ACTION_LIST}
  validates :action, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @team = Team.find(params[:team_id])
    collection = EventCollection.create(params)
    
    respond_to do |format|
      format.html do
        self.current_team = @team
        @event_group = collection.to_group_data
        @days = @event_group.keys.sort {|x, y| y <=> x}
      end
      format.json do
        render json: collection.to_hash_group_data
      end
    end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper

  def show_missing_partial(e)
    e.message[0..(e.message.index(',') - 1)]
  end
  
end

app/views/events/_assign_todo.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">给 <%= item.new_u_name %> 指派了任务:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/_comment_todo.html.erb
<div class="event event-comment">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">回复了任务:  </span>
  <span class="event-text"><%= link_to item.s_cm_todo_content, item.s_cm_todo_path %></span>
  <div class="event-body">
    <%= link_to item.s_cm_content, item.s_cm_path %>
  </div>
</div>

app/views/events/_complete_todo.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">完成了任务:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/_create_project.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">创建了项目:  </span>
  <span class="event-text"><%= link_to item.s_proj_name, team_project_path(current_team.id, item.s_proj_id) %></span>
</div>

app/views/events/_create_team.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">创建了团队:  </span>
  <span class="event-text"><%= item.s_team_name %></span>
</div>

app/views/events/_create_todo.html.erb
<div class="event">
  
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">创建了任务:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/_delete_todo.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action">删除了任务:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/_edit_assign_todo.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action"> 把 <%= item.old_u_name %> 的任务指派给 <%= item.new_u_name %>:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/_edit_todo_deadlines.html.erb
<div class="event">
  <a href="#event-<%= item.event_id %>" class="event-created-at"><%= item.created_hm %></a>
  <span class="event-actor">
    <%= link_to item.user_name, member_path(item.user_id) %>
  </span>
  <span class="event-action"> 将任务完成时间从 <%= item.pretty_old_deadlines %> 修改为 <%= item.pretty_new_deadlines %>:  </span>
  <span class="event-text"><%= link_to item.todo_content, item.todo_path %></span>
</div>

app/views/events/index.html.erb
<div class="page page-root">
  <div class="page-inner" id="page-events">
    <% @days.each do |day| %>
      <div class="events-day">
	<% pday = PrettyDay.new(day) %>
        <h4 class="events-day-title">
	  <% if pday.is_tty? %>
	    <%= pday.cn_tty %>
	  <% else %>
	    <span class="date"><%= pday.month_day %></span>
	    <span class="day"><%= pday.cn_week %></span>
	  <% end %>
	</h4>
	<% cates = @event_group[day] %>
	<div class="events-day-content">
	  <% cates.each do |cate| %>
	    <div class="events-ancestor">
	      <h5 class="events-ancestor-title"><%= link_to cate.name, cate.link_path(@team) %></h5>
	      <% cate.items.each do |item| %>
		<% begin %>
		  <%= render item.action, item: item %>
		<% rescue ActionView::MissingTemplate => e %>
		<p><%= show_missing_partial(e) %></p>
		<% end %>
	      <% end %>
	    </div>
	  <% end %>
	</div>
      </div>
    <% end %>
  </div>
</div>